
let lesson_id = 1;

let lesson_metacontent = 
{
    "CATN": "Language",
    "CATT": 6,
    "CID": 1031,
    "EID": 1,
    "ENCODE": "6502",
    "LVLT": 3,
    "PUBD": "2015/10/1 0:00:00",
    "ST": "你好",
    "TRE": "Hello!",
    "TRJ": "こんにちは",
    "TT": "你好",
    "Version": 5,
    "lastUpdateTime": 1543500654500
};

let lesson_content = 
[
  {
    "STRE": "A:Hello!",
    "STRJ": "A:こんにちは！",
    "SortId": 1,
    "Words": [
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "A",
        "SortId": 1,
        "TW": "A",
        "WID": 10001,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": ":",
        "SortId": 2,
        "TW": ":",
        "WID": 10002,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Hello",
        "JP": "こんにちは",
        "KW": "Y",
        "PY": "nǐhǎo",
        "SW": "你好",
        "SortId": 3,
        "TW": "你好",
        "WID": 10003,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "！",
        "SortId": 4,
        "TW": "！",
        "WID": 10004,
        "isKeyword": false,
        "lastStudyTime": -1
      }
    ]
  },
  {
    "STRE": "B:Hello!",
    "STRJ": "B:こんにちは！",
    "SortId": 2,
    "Words": [
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "B",
        "SortId": 1,
        "TW": "B",
        "WID": 10005,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": ":",
        "SortId": 2,
        "TW": ":",
        "WID": 10006,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Hello",
        "JP": "こんにちは",
        "KW": "Y",
        "PY": "nǐhǎo",
        "SW": "你好",
        "SortId": 3,
        "TW": "你好",
        "WID": 10007,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "！",
        "SortId": 4,
        "TW": "！",
        "WID": 10008,
        "isKeyword": false,
        "lastStudyTime": -1
      }
    ]
  },
  {
    "STRE": "A:My name is Lily. What is your name?",
    "STRJ": "A:わたしは李丽といいます。あなたは?",
    "SortId": 3,
    "Words": [
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "A",
        "SortId": 1,
        "TW": "A",
        "WID": 10009,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": ":",
        "SortId": 2,
        "TW": ":",
        "WID": 10010,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "I;me",
        "JP": "私;僕",
        "KW": "Y",
        "PY": "wǒ",
        "SW": "我",
        "SortId": 3,
        "TW": "我",
        "WID": 10011,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Name;call",
        "JP": "（名前は）…という;呼ぶ",
        "KW": "Y",
        "PY": "jiào",
        "SW": "叫",
        "SortId": 4,
        "TW": "叫",
        "WID": 10012,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Lily",
        "JP": "李麗（中国人の名前）",
        "KW": "N",
        "PY": "lǐlì",
        "SW": "李丽",
        "SortId": 5,
        "TW": "李麗",
        "WID": 10013,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "，",
        "SortId": 6,
        "TW": "，",
        "WID": 10014,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "You",
        "JP": "あなた",
        "KW": "Y",
        "PY": "nǐ",
        "SW": "你",
        "SortId": 7,
        "TW": "你",
        "WID": 10015,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Name;call",
        "JP": "（名前は）…という;呼ぶ",
        "KW": "Y",
        "PY": "jiào",
        "SW": "叫",
        "SortId": 8,
        "TW": "叫",
        "WID": 10016,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "What",
        "JP": "何\b",
        "KW": "N",
        "PY": "shénme",
        "SW": "什么",
        "SortId": 9,
        "TW": "什么",
        "WID": 10017,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Name",
        "JP": "名前",
        "KW": "N",
        "PY": "míngzi",
        "SW": "名字",
        "SortId": 10,
        "TW": "名字",
        "WID": 10018,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "？",
        "SortId": 11,
        "TW": "？",
        "WID": 10019,
        "isKeyword": false,
        "lastStudyTime": -1
      }
    ]
  },
  {
    "STRE": "B:My name is GaoPing. Nice to meet you.",
    "STRJ": "B:僕は高平といいます。はじめまして。",
    "SortId": 4,
    "Words": [
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "B",
        "SortId": 1,
        "TW": "B",
        "WID": 10020,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": ":",
        "SortId": 2,
        "TW": ":",
        "WID": 10021,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "I;me",
        "JP": "私;僕",
        "KW": "Y",
        "PY": "wǒ",
        "SW": "我",
        "SortId": 3,
        "TW": "我",
        "WID": 10022,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Name;call",
        "JP": "（名前は）…という;呼ぶ",
        "KW": "Y",
        "PY": "jiào",
        "SW": "叫",
        "SortId": 4,
        "TW": "叫",
        "WID": 10023,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Gao Ping",
        "JP": "高平（中国人の名前）",
        "KW": "N",
        "PY": "gāopíng",
        "SW": "高平",
        "SortId": 5,
        "TW": "高平",
        "WID": 10024,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "，",
        "SortId": 6,
        "TW": "，",
        "WID": 10025,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Very",
        "JP": "とても;非常に",
        "KW": "N",
        "PY": "hěn",
        "SW": "很",
        "SortId": 7,
        "TW": "很",
        "WID": 10026,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Happy",
        "JP": "ハッピー",
        "KW": "N",
        "PY": "gāoxìng",
        "SW": "高兴",
        "SortId": 8,
        "TW": "高興",
        "WID": 10027,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Know",
        "JP": "見知る;知っている",
        "KW": "N",
        "PY": "rènshi",
        "SW": "认识",
        "SortId": 9,
        "TW": "認識",
        "WID": 10028,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "You",
        "JP": "あなた;君",
        "KW": "N",
        "PY": "nǐ",
        "SW": "你",
        "SortId": 10,
        "TW": "你",
        "WID": 10029,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "！",
        "SortId": 11,
        "TW": "！",
        "WID": 10030,
        "isKeyword": false,
        "lastStudyTime": -1
      }
    ]
  },
  {
    "STRE": "A:Nice to meet you.",
    "STRJ": "A:はじめまして。",
    "SortId": 5,
    "Words": [
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "A",
        "SortId": 1,
        "TW": "A",
        "WID": 10031,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": ":",
        "SortId": 2,
        "TW": ":",
        "WID": 10032,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Very",
        "JP": "とても;非常に\b",
        "KW": "N",
        "PY": "hěn",
        "SW": "很",
        "SortId": 3,
        "TW": "很",
        "WID": 10033,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Happy",
        "JP": "嬉しい;喜ぶ",
        "KW": "N",
        "PY": "gāoxìng",
        "SW": "高兴",
        "SortId": 4,
        "TW": "高興",
        "WID": 10034,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "Know",
        "JP": "見知る;知っている",
        "KW": "N",
        "PY": "rènshi",
        "SW": "认识",
        "SortId": 5,
        "TW": "認識",
        "WID": 10035,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "You",
        "JP": "あなた;君",
        "KW": "N",
        "PY": "nǐ",
        "SW": "你",
        "SortId": 6,
        "TW": "你",
        "WID": 10036,
        "isKeyword": false,
        "lastStudyTime": -1
      },
      {
        "CID": 0,
        "EID": 0,
        "EN": "",
        "JP": "",
        "KW": "N",
        "PY": "",
        "SW": "！",
        "SortId": 7,
        "TW": "！",
        "WID": 10037,
        "isKeyword": false,
        "lastStudyTime": -1
      }
    ]
  }
];